global:
  # scrape_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout: 3s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing 2 different jobs with multiple endpoints to scrape:
scrape_configs:
  
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'services targets'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 3s
    file_sd_configs: 
      - files:
          - monitor_targets_*.yml
        refresh_interval: 5s
        