cluster:
  name: logging-cluster

node:
  name: node-elasticsearch

network:
  host: localhost

http.port: 9200-9300

discovery:
  zen:
    minimum_master_nodes: 1

script.painless.regex.enabled: true
# xpack.ssl.certificate_authorities: /usr/share/elasticsearch/data/letsencrypt.pem
